Settings:
  AllowedToBeOp:
  - JackyYT
  - Epson
  - HarunGamesBH
  - ItzLuka_
  DeopMessage: '&c&lI&f&lN &8» &7Ne mozes se OP-at!'
                                                                        